---
- name: Machine inventory
  hosts: all
  gather_facts: yes
  tasks:
    - name: Generate CSV file
      become: yes
      lineinfile:
        path: "/tmp/file.csv"
        line: '{{ansible_hostname}},{{ansible_default_ipv4.address}},{{ansible_distribution}},{{ansible_kernel}}'
        create: true
