---
- name: Machine inventory
  hosts: all
  gather_facts: yes
  tasks:
    - name: Fetch Java version
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version

    - name: Generate CSV file
      become: yes
      lineinfile:
        path: "/tmp/file.csv"
        line: '{{ansible_hostname}},{{ansible_default_ipv4.address}},{{ansible_distribution}},{{ansible_kernel}},{{java_version.stdout}}'
        create: true
